package org.example.recyclingtransaction;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-05T10:07:37.332+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "recyclingTransaction", 
                  wsdlLocation = "file:/home/jorrit/Dropbox/uni/bachpro/java/src/main/resources/recyclingTransaction.wsdl",
                  targetNamespace = "http://www.example.org/recyclingTransaction/") 
public class RecyclingTransaction_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/recyclingTransaction/", "recyclingTransaction");
    public final static QName RecyclingTransactionSOAP = new QName("http://www.example.org/recyclingTransaction/", "recyclingTransactionSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/jorrit/Dropbox/uni/bachpro/java/src/main/resources/recyclingTransaction.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecyclingTransaction_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Dropbox/uni/bachpro/java/src/main/resources/recyclingTransaction.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecyclingTransaction_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecyclingTransaction_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecyclingTransaction_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecyclingTransaction_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecyclingTransaction_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecyclingTransaction_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RecyclingTransaction
     */
    @WebEndpoint(name = "recyclingTransactionSOAP")
    public RecyclingTransaction getRecyclingTransactionSOAP() {
        return super.getPort(RecyclingTransactionSOAP, RecyclingTransaction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecyclingTransaction
     */
    @WebEndpoint(name = "recyclingTransactionSOAP")
    public RecyclingTransaction getRecyclingTransactionSOAP(WebServiceFeature... features) {
        return super.getPort(RecyclingTransactionSOAP, RecyclingTransaction.class, features);
    }

}
