package org.example.recyclingtransaction;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-09T10:28:42.994+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.example.org/recyclingTransaction/", name = "recyclingTransaction")
@XmlSeeAlso({ObjectFactory.class})
public interface RecyclingTransaction {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "addTransaction", targetNamespace = "http://www.example.org/recyclingTransaction/", className = "org.example.recyclingtransaction.AddTransaction")
    @WebMethod(action = "http://www.example.org/recyclingTransaction/addTransaction")
    @ResponseWrapper(localName = "addTransactionResponse", targetNamespace = "http://www.example.org/recyclingTransaction/", className = "org.example.recyclingtransaction.AddTransactionResponse")
    public java.lang.String addTransaction(
        @WebParam(name = "userID", targetNamespace = "")
        java.lang.String userID,
        @WebParam(name = "locationID", targetNamespace = "")
        java.lang.String locationID,
        @WebParam(name = "timestamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timestamp,
        @WebParam(name = "paper", targetNamespace = "")
        int paper,
        @WebParam(name = "plastic", targetNamespace = "")
        int plastic,
        @WebParam(name = "glass", targetNamespace = "")
        int glass,
        @WebParam(name = "metal", targetNamespace = "")
        int metal
    );

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "addTransactiontext", targetNamespace = "http://www.example.org/recyclingTransaction/", className = "org.example.recyclingtransaction.AddTransactiontext")
    @WebMethod(action = "http://www.example.org/recyclingTransaction/addTransactiontext")
    @ResponseWrapper(localName = "addTransactiontextResponse", targetNamespace = "http://www.example.org/recyclingTransaction/", className = "org.example.recyclingtransaction.AddTransactiontextResponse")
    public java.lang.String addTransactiontext(
        @WebParam(name = "transaction", targetNamespace = "")
        java.lang.String transaction
    );
}
