
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.recyclingtransaction;

import java.util.logging.Logger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-05T10:07:36.602+02:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "recyclingTransaction",
                      portName = "recyclingTransactionSOAP",
                      targetNamespace = "http://www.example.org/recyclingTransaction/",
                      wsdlLocation = "file:/home/jorrit/Dropbox/uni/bachpro/java/src/main/resources/recyclingTransaction.wsdl",
                      endpointInterface = "org.example.recyclingtransaction.RecyclingTransaction")
                      
public class RecyclingTransactionImpl implements RecyclingTransaction {

    private static final Logger LOG = Logger.getLogger(RecyclingTransactionImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.recyclingtransaction.RecyclingTransaction#addTransaction(java.lang.String  userID ,)java.lang.String  locationID ,)javax.xml.datatype.XMLGregorianCalendar  timestamp ,)int  paper ,)int  plastic ,)int  glass ,)int  metal )*
     */
    public java.lang.String addTransaction(java.lang.String userID,java.lang.String locationID,javax.xml.datatype.XMLGregorianCalendar timestamp,int paper,int plastic,int glass,int metal) { 
        LOG.info("Executing operation addTransaction");
        System.out.println(userID);
        System.out.println(locationID);
        System.out.println(timestamp);
        System.out.println(paper);
        System.out.println(plastic);
        System.out.println(glass);
        System.out.println(metal);
        QueueConnection.addToQueue(userID +", "+ locationID +", "+ timestamp.toGregorianCalendar().getTime().getTime() +", "+ paper +", "+ plastic +", "+ glass +", "+ metal); 
        try {
            java.lang.String _return = "_return1774161639";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.recyclingtransaction.RecyclingTransaction#addTransactiontext(java.lang.String  transaction )*
     */
    public java.lang.String addTransactiontext(java.lang.String transaction) { 
        LOG.info("Executing operation addTransactiontext");
        System.out.println(transaction);
        try {
            java.lang.String _return = "_return-1824603211";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
