
package org.example.recyclingtransaction;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.UUID;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-09T10:28:58.289+02:00
 * Generated source version: 2.7.11
 * 
 */
public final class RecyclingTransaction_RecyclingTransactionSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/recyclingTransaction/", "recyclingTransaction");

    private RecyclingTransaction_RecyclingTransactionSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RecyclingTransaction_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RecyclingTransaction_Service ss = new RecyclingTransaction_Service(wsdlURL, SERVICE_NAME);
        RecyclingTransaction port = ss.getRecyclingTransactionSOAP();  
        
        {
        System.out.println("Invoking addTransaction...");
        java.lang.String _addTransaction_userID = UUID.randomUUID().toString();
        java.lang.String _addTransaction_locationID = UUID.randomUUID().toString();
        javax.xml.datatype.XMLGregorianCalendar _addTransaction_timestamp = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-05-09T10:28:58.324+02:00");
        int _addTransaction_paper = 172;
        int _addTransaction_plastic = 573;
        int _addTransaction_glass = 98;
        int _addTransaction_metal = 485;
        java.lang.String _addTransaction__return = port.addTransaction(_addTransaction_userID, _addTransaction_locationID, _addTransaction_timestamp, _addTransaction_paper, _addTransaction_plastic, _addTransaction_glass, _addTransaction_metal);
        System.out.println("addTransaction.result=" + _addTransaction__return);


        }
        /*{
        System.out.println("Invoking addTransactiontext...");
        java.lang.String _addTransactiontext_transaction = "_addTransactiontext_transaction-1967590135";
        java.lang.String _addTransactiontext__return = port.addTransactiontext(_addTransactiontext_transaction);
        System.out.println("addTransactiontext.result=" + _addTransactiontext__return);


        }*/

        System.exit(0);
    }

}
