
package org.example.recyclingtransaction;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.UUID;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-27T09:56:48.278+02:00
 * Generated source version: 2.7.11
 * 
 */
public class RecyclingTransaction_RecyclingTransactionSOAP_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://www.example.org/recyclingTransaction/",
			"recyclingTransaction");

	private RecyclingTransaction_RecyclingTransactionSOAP_Client() {
	}

	private void generateData() throws DatatypeConfigurationException {
		URL wsdlURL = RecyclingTransaction_Service.WSDL_LOCATION;
		// if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
		// File wsdlFile = new File(args[0]);
		// try {
		// if (wsdlFile.exists()) {
		// wsdlURL = wsdlFile.toURI().toURL();
		// } else {
		// wsdlURL = new URL(args[0]);
		// }
		// } catch (MalformedURLException e) {
		// e.printStackTrace();
		// }
		// }
		/*
		 * username | userid -----------+--------------------------------------
		 * ckramer | 39659b52-97e4-4513-b3b9-4061974c9bd5 
		 * jseinfeld | a30f1f78-ce11-4f52-963c-40ff1903cb10 
		 * ebenes | fe9140a4-a18d-47ad-8fb6-8c85d3a5f7d8 
		 * nycadmin | 85f81b76-30c5-415a-b03d-77a3be842705 
		 * gcostanza | 6ab62cc1-d858-48f6-b52f-194203bdade3
		 */
		ArrayList<String> userids = new ArrayList<>();
		userids.add("39659b52-97e4-4513-b3b9-4061974c9bd5");
		userids.add("a30f1f78-ce11-4f52-963c-40ff1903cb10");
		userids.add("fe9140a4-a18d-47ad-8fb6-8c85d3a5f7d8");
		userids.add("6ab62cc1-d858-48f6-b52f-194203bdade3");

		/*
		 * locationname | locationid
		 * --------------------+-------------------------------------- Jet
		 * Propulsion Lab | 3cb24832-f1b7-4b1c-a191-e644c8574142 
		 * Kwik-E-Mart | 484f7753-adbe-45ae-b1d9-492c6c5a1c07 
		 * Area 51 | a3ca2c55-58a6-4edc-b242-e3d353ea74af
		 */

		ArrayList<String> locationids = new ArrayList<>();
		locationids.add("3cb24832-f1b7-4b1c-a191-e644c8574142");
		locationids.add("484f7753-adbe-45ae-b1d9-492c6c5a1c07");
		locationids.add("a3ca2c55-58a6-4edc-b242-e3d353ea74af");

		RecyclingTransaction_Service ss = new RecyclingTransaction_Service(
				wsdlURL, SERVICE_NAME);
		RecyclingTransaction port = ss.getRecyclingTransactionSOAP();

		Random rand = new Random();
		
		Date offset = new Date();
		Date end = new Date();
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");

		try {
			offset = sdf.parse("2014-01-01T00:00:00.000+0200");
			end = sdf.parse("2014-12-31T23:59:59.999+0200");
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		long diff = end.getTime() - offset.getTime() + 1;
		
		for(int i = 0; i < 100; i++) {
			System.out.println("Invoking addTransaction..." + userids.size() + ", " + locationids.size());
			java.lang.String _addTransaction_userID = userids.get(rand
					.nextInt(userids.size()));
			java.lang.String _addTransaction_locationID = locationids.get(rand
					.nextInt(locationids.size()));

			java.util.GregorianCalendar randDate = new java.util.GregorianCalendar();
			randDate.setTime(new Date(offset.getTime()
					+ (long) (Math.random() * diff)));
			XMLGregorianCalendar _addTransaction_timestamp = javax.xml.datatype.DatatypeFactory
					.newInstance().newXMLGregorianCalendar(randDate);
			_addTransaction_timestamp.toGregorianCalendar().getTimeInMillis();
			int _addTransaction_paper = rand.nextInt(1001);
			int _addTransaction_plastic = rand.nextInt(1001);
			int _addTransaction_glass = rand.nextInt(1001);
			int _addTransaction_metal = rand.nextInt(1001);
			System.out.println(_addTransaction_userID + ", " + _addTransaction_locationID  + ", " + 
					_addTransaction_timestamp  + ", " + _addTransaction_paper  + ", " + 
					_addTransaction_plastic + ", " + _addTransaction_glass  + ", " + 
					_addTransaction_metal);
			java.lang.String _addTransaction__return = port.addTransaction(
					_addTransaction_userID, _addTransaction_locationID,
					_addTransaction_timestamp, _addTransaction_paper,
					_addTransaction_plastic, _addTransaction_glass,
					_addTransaction_metal);
			System.out.println("addTransaction.result="
					+ _addTransaction__return);
		}

	}

	public static void main(String args[]){
		RecyclingTransaction_RecyclingTransactionSOAP_Client rt = new RecyclingTransaction_RecyclingTransactionSOAP_Client();
		try {
			rt.generateData();
		} catch (DatatypeConfigurationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		//System.out.println(System.getProperty("user.name"));
		/*
		 * { System.out.println("Invoking addTransactiontext...");
		 * java.lang.String _addTransactiontext_transaction =
		 * "_addTransactiontext_transaction-1967590135"; java.lang.String
		 * _addTransactiontext__return =
		 * port.addTransactiontext(_addTransactiontext_transaction);
		 * System.out.println("addTransactiontext.result=" +
		 * _addTransactiontext__return);
		 * 
		 * 
		 * }
		 */

		System.exit(0);
	}

}
